name: 'FORK: Serverless with Python Requirements (with Working Directory)'
description: 'Javascript action that runs a Serverless deploy using the serverless-python-requirements plugin.'

runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: 'fast-forward'
  color: 'red'
